image: node:11.13.0

pipelines:
  branches:
    master:
      - step:
          name: Deploy
          caches:
            - node
          script:
            - pipe: atlassian/ssh-run:0.2.5
              variables:
                SSH_USER: 'root'
                SERVER: '93.190.143.5'
                COMMAND: 'cd /var/www/dev-full-admin && git pull && composer install'
